### ISSUE TITLE
安卓如果应用被杀死，但后台保持可自启状态，能收到推送但启动应用后不能执行跳转页面逻辑

### ISSUE THREAD

**Issue by Star945** [jpush/jpush-hbuilder-demo#10]
收到消息 应用未开启，点消息 应用启动---启动后无法执行跳转逻辑同样也获取不到消息信息，因为应用起来后 事件侦听还没有被初始化，求问解决办法~

**Comment by JoshLipan** [comment]
更新版本v1.1.0，配合[获取和清除点击通知内容缓存API](https://github.com/jpush/jpush-hbuilder-demo/blob/master/API.md#获取点击通知内容缓存)可以解决此问题
