### ISSUE TITLE
Hbuilder 在Androidstudio 中集成极光推送运行显示空白页

### ISSUE THREAD

**Issue by chenshen** [jpush/jpush-hbuilder-demo#11]
完全按你们的官方下载的demo修改的，每次运行都是显示空白
![image](https://user-images.githubusercontent.com/4024766/33261741-c775b908-d39e-11e7-898a-dc42bd4c0957.png)帮忙看下究竟是什么原因造成的。

**Comment by lhw5123** [comment]
你是怎么修改的？
