### ISSUE TITLE
你好，hbuilder新的离线打包环境已经没有PGPush.h接口暴露

### ISSUE THREAD

**Issue by zlyyy** [jpush/jpush-hbuilder-demo#12]
你好，hbuilder新的离线打包环境已经没有PGPush.h接口暴露
因为需要支持iphonex，不得不把打包环境升级，但是hbuilder新的离线打包环境已经没有PGPush.h接口暴露，之前贵司给出的推送方案基于此，此方式已经不能正常使用了，不知道该如何解决。谢过

**Comment by huangminlinux** [comment]
对于这个问题之前想尝试处理，不过官方提供的几种 demo  [getui](https://github.com/dcloudio/H5P.iOS/blob/master/libPush/GeTuiPush/GeTuiPush/PGPushActualize.h#L11) 和 [小米](https://github.com/dcloudio/H5P.iOS/blob/master/libPush/XiaomiPush/XiaomiPush/PGPushActualize.h#L9) 也是引入 `PGPush.h` 这个头文件貌似很久没更新了，我看 HBuilder 论坛提了一个类似的[问题](http://ask.dcloud.net.cn/question/50342)，不清楚为什么现在还没有答复。

你可以把 demo 中 PGPush.h 复制到自己的工程中。

**Comment by zlyyy** [comment]
你好，我一开始以为 PGPush.h 复制过去就可以，结果发现 PGPush.h 里面的回调都不成功了，已经没办法正常是使用了。getui和小米是官方打包环境集成了，只需要配个appkey就可以使用了。谢过

**Comment by huangminlinux** [comment]
需要在 `Appdelegate.m` 文件中的 `didRegisterForRemoteNotificationsWithDeviceToken` 方法中添加右边这段代码`[JPUSHService registerDeviceToken:deviceToken];` ，注意需要导入头文件` import "JPUSHService.h"`

你好刚刚做了更新支持了 iOS 10 的事件，可以更新一下。

**Comment by zlyyy** [comment]
你好，感谢贵司这么及时的更新。我上午更新了一下，JPUSHService.h文件被删掉了吗，JPUSHRegisterDelegate，JPUSHRegisterEntity这些提示找不到，是我这边少了什么文件吗

**Comment by huangminlinux** [comment]
是个失误，可以更新一下。已经加上了。

**Comment by zlyyy** [comment]
测试通过，代表全猿类，谢谢您，谢谢贵司
