### ISSUE TITLE
jpush-hbuilder-demo问题

### ISSUE THREAD

**Issue by david-wei-zh** [jpush/jpush-hbuilder-demo#17]
我把demo都按照离线打包的方式放在android  然后手机打开一直卡在hbuilder界面里 什么情况  demo都是官方提示做的  自问没少哪一步  还是不行

**Comment by lhw5123** [comment]
有日志吗？

**Comment by david-wei-zh** [comment]
日志已经发给你了

**Comment by lhw5123** [comment]
不太理解「把demo都按照离线打包的方式放在android」是什么意思。现在这个 demo 已经是一个可以直接运行的 Android 项目了。能说下你的具体操作过程吗？
你发的日志里搜索了下，没找到有 JPush 的相关日志。

**Comment by david-wei-zh** [comment]
我先 在android studio里面建项目 按照离线打包的例子做的  然后把我的hbuilder项目需要的所有文件全部拷贝到android studio里面的asstes->apps->H51423BFB(这个是我的appid)->www内，然后根据你们官方的demo集成指南配置io.dcloud等，依照步骤走的  然后android打包运行不行

**Comment by david-wei-zh** [comment]
还有问题  我hbuilder  用到百度地图的lbs开发  里面有地图配置  把hbuilder内的文件全都拷过来就能用  还是要参照Feature-Android。xls去配置

**Comment by lhw5123** [comment]
不添加 JPush 的东西可以运行吗？你把你的项目和 demo 比对下，demo 是测试可以运行的。

**Comment by david-wei-zh** [comment]
这回提示打包时未添加device模块 navigator模块

**Comment by 1084588510** [comment]
demo 是可以成功，但是我把builder换成自己的就各种错误根本不行，根据你们写的文档集成也是根本不行！

**Comment by JoshLipan** [comment]
没看懂builder换成自己的是什么意思，你先根据hbuilder离线打包集成自己的应用，成功运行后再集成极光插件试试 @1084588510
