### ISSUE TITLE
【报bug】点击推送通知，不触发openNotification事件

### ISSUE THREAD

**Issue by iceychan** [jpush/jpush-hbuilder-demo#22]
1、IOS的Demo中的jpush.js未更新，不存在openNotificationIniOSCallback方法，使用最新的jpush.js替换后仍不触发openNotification事件。
2、JPushPlugin.m中
`NSString *const kJPushOpenNotification  = @"plus.Push.receiveNotificationIniOSCallback";    //前台收到推送消息`
需修改为
`NSString *const kJPushOpenNotification  = @"plus.Push.openNotificationIniOSCallback";    //触发推送通知事件`

**Comment by huangminlinux** [comment]
已更新
