### ISSUE TITLE
集成之后能接受到推送信息，但是不调用receiveNotification和openNotification是为什么？

### ISSUE THREAD

**Issue by Suppermanone** [jpush/jpush-hbuilder-demo#28]

**Comment by JoshLipan** [comment]
参照[Demo 事件注册](https://github.com/jpush/jpush-hbuilder-demo/blob/3216648045d1117fa92df62de41e08beb4a4d172/push.html#L98)

**Comment by Suppermanone** [comment]
我是直接把demo里的push.html直接放到自己项目里的，可以接收到推送，就是无法调用这两个方法。demo里面的可以调用，不知道是不是哪个地方配置错误还是什么原因。。

**Comment by JoshLipan** [comment]
哪个平台的

**Comment by Suppermanone** [comment]
Android的

**Comment by JoshLipan** [comment]
按照[集成指南](https://github.com/jpush/jpush-hbuilder-demo#%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97)检查一遍你的配置
