### ISSUE TITLE
iOS 设置别名问题

### ISSUE THREAD

**Issue by Suppermanone** [jpush/jpush-hbuilder-demo#32]
iOS设置别名，在极光后台给设置的别名发送推送，无法发送，错误是：“此别名或者标签还没有在任何客户端SDK提交设置成功。“在Android端别名可以接收到推送！

**Comment by huangminlinux** [comment]
检查原生 的 setTag 是否有成功触发。

**Comment by Suppermanone** [comment]
找到原因了是因为别名没设置成功，有的时候连接极光后台会出现连接超时的情况，导致别名设置不成功！
