### ISSUE TITLE
ios上点击通知进去，不会触发openNotification方法

### ISSUE THREAD

**Issue by zlhpipi** [jpush/jpush-hbuilder-demo#33]
ios上点击通知进去，不会触发openNotification方法，另外我获取extras里的一个参数newsid，是否可以这样写newsid=plus.Push.openNotification.extras.newsid;

**Comment by zlhpipi** [comment]
也就是说我想点击通知后，打开我的一个页面

**Comment by zlhpipi** [comment]
在APP外面打开通知和在里面打开通知有区别吗？

**Comment by huangminlinux** [comment]
- 你要通过监听来获取openNotification 的字段，具体参考 [opennotification](https://github.com/jpush/jpush-hbuilder-demo/blob/master/API.md#event---jpushopennotification)
- 另外 iOS 和 android 返回的字段还不一样，android 的 extras 放到 extras 属性里面。  iOS 没有 extra 属性，extra 的信息放到外层，具体输出一下 事件返回的参数就清楚了。

**Comment by zlhpipi** [comment]
现在是我监听了openNotification 方法，但是我点击通知时，并没有触发这个方法

**Comment by zlhpipi** [comment]
设置角标也不起作用

**Comment by huangminlinux** [comment]
能收到推送，事件没回调？

**Comment by zlhpipi** [comment]
推送是收到了，但是点击推送过来的通知，点击进去，触发不了opennotification方法

**Comment by huangminlinux** [comment]
iOS 几？

**Comment by zlhpipi** [comment]
是hbuilder写的，用ios离线打包

**Comment by zlhpipi** [comment]
xcode9.4，ios11.4版本

**Comment by zlhpipi** [comment]
另外，这个角标，我点了消息通知后，但是角标的数字不会减

**Comment by huangminlinux** [comment]
- JS 文件导入没？
- 要将 badge 设为 0 才会消失 调用这个方法，setApplicationIconBadgeNumber。

**Comment by zlhpipi** [comment]
导入了

**Comment by huangminlinux** [comment]
这就奇怪了，加我Q了解一下具体情况Q: 380108184

**Comment by zlhpipi** [comment]
我加你了

**Comment by huangminlinux** [comment]
可以更新到最新版本。
