### ISSUE TITLE
andriod集成极光推送时报错More than one file was found with OS independent path 'io/dcloud/all.js'

### ISSUE THREAD

**Issue by zlhpipi** [jpush/jpush-hbuilder-demo#36]
andriod集成极光推送时报错More than one file was found with OS independent path 'io/dcloud/all.js'

**Comment by JoshLipan** [comment]
jpush插件不涉及'io/dcloud/all.js'这个文件，需要你自己检查下了

**Comment by zlhpipi** [comment]
我只是把demo里的jar包复制过来，还有io/dcloud下的文件复制过来，按照教程上做了些设置

**Comment by zlhpipi** [comment]
运行就这样了

**Comment by JoshLipan** [comment]
先参照hbuilder提供的离线打包教程集成你的项目，成功运行后，再集成jpush的插件，不要直接复制demo的jar

**Comment by zlhpipi** [comment]
我已经按照离线打包的教程集成了我的项目了，已经是正常运行了，但是一拷进来极光的东西就报错了

**Comment by zlhpipi** [comment]
怎么集成jpush的插件？

**Comment by JoshLipan** [comment]
涉及到极光的jar包是通过jcenter自动集成的，不需要你自己拷贝

**Comment by zlhpipi** [comment]
一个jar包都不用拷？

**Comment by JoshLipan** [comment]
看[集成指南](https://github.com/jpush/jpush-hbuilder-demo#%E9%9B%86%E6%88%90%E6%8C%87%E5%8D%97)

**Comment by zlhpipi** [comment]
按照集成指南设置好以后，JPushReceiver文件报错

**Comment by JoshLipan** [comment]
报什么错误

**Comment by zlhpipi** [comment]
那个文件是红的

**Comment by zlhpipi** [comment]
运行时报：Installation failed width message Failed to finalize session:INSTALL_FAILED_ABORTED:User rejected permissions.

**Comment by zlhpipi** [comment]
Installation failed with message Failed to finalize session : INSTALL_FAILED_ABORTED: User rejected permissions.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

**Comment by zlhpipi** [comment]
清理过一遍工程，重新运行，还是有错E/UncaughtExceptionHandler: java.lang.UnsatisfiedLinkError: No implementation found for int com.baidu.platform.comjni.tools.JNITools.initClass(java.lang.Object, int) (tried Java_com_baidu_platform_comjni_tools_JNITools_initClass and Java_com_baidu_platform_comjni_tools_JNITools_initClass__Ljava_lang_Object_2I)
I/Process: Sending signal. PID: 17125 SIG: 9
Application terminated.

**Comment by JoshLipan** [comment]
用你当前的环境运行下官网demo试试

**Comment by zlhpipi** [comment]
直接运行不了

**Comment by JoshLipan** [comment]
加我qq了解下：542938192

**Comment by zlhpipi** [comment]
加了

**Comment by zlhpipi** [comment]
问题已解决

**Comment by zlhpipi** [comment]
主要是集成的时候，里面有很多的jar包没有用到，可能有些有冲突，我把不要的jar包和引有清除了，再集成极光就成功了。但是收不到通知，原来是后台没有绑定应用包名

**Comment by zlhpipi** [comment]
后台绑定好应用包名就可以收到通知了
