### ISSUE TITLE
官方DEMO正常，自己的项目里却报Not get deviceToken yet.什么原因？

### ISSUE THREAD

**Issue by cz848** [jpush/jpush-hbuilder-demo#4]
完全一样的证书和buddle id丢进去，却出现了不同的结果，确认完全按照示例去集成，xcode 8

**Comment by cz848** [comment]
didRegisterForRemoteNotificationsWithDeviceToken和didFailToRegisterForRemoteNotificationsWithError一个没走到

**Comment by huangminlinux** [comment]
这个项目比较老旧， 之后会适配新版本的 HBuilder 。
暂时可以通过 在 Appdelegate.m 里面的 `didRegisterForRemoteNotificationsWithDeviceToken `方法中加入下面代码， 例如：

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
        [PDRCore handleSysEvent:PDRCoreSysEventRevDeviceToken withObject:deviceToken];
        [JPUSHService registerDeviceToken:deviceToken]; // 加入这一句
}
```

**Comment by cz848** [comment]
谢谢回复，不过我说的是didRegisterForRemoteNotificationsWithDeviceToken和didFailToRegisterForRemoteNotificationsWithError都走不到，所以我加了也没用。

**Comment by huangminlinux** [comment]
1. 推送证书配置好没？
2. TARGETS -> Capabilities -> Push Notification 点开没?
3. 应用启动，有弹出推送请求权限没？

**Comment by cz848** [comment]
1.相同设置demo正常，所以不存在配置问题。
2.这个我还是知道的。
3.第一次安装的时候会请求消息权限。而且设置里也是正常的。

**Comment by huangminlinux** [comment]
具体看不出什么原因。
检查 bundle id 是否一样，
确保真机运行。

**Comment by cz848** [comment]
定位不了问题吗？

**Comment by huangminlinux** [comment]
不清楚你那边情况， 如果是 demo 工程 可以发我Q：380108184 看看
