### ISSUE TITLE
android引入报错

### ISSUE THREAD

**Issue by yoyo0926** [jpush/jpush-hbuilder-demo#44]
import io.dcloud.common.DHInterface.IWebview;
import io.dcloud.common.DHInterface.StandardFeature;
import io.dcloud.common.util.JSUtil;

这三个类hbuilder引入报错

**Comment by JoshLipan** [comment]
这三个类是 Hbuilder 类，属于 libs/pdr.jar，建议检查下是否引入成功。非 JPush 问题关闭。
