### ISSUE TITLE
Android点击消息将重启应用

### ISSUE THREAD

**Issue by lemon-go** [jpush/jpush-hbuilder-demo#5]
收到**通知消息**后，会**重启应用**（当前应用已运行在前台），重启后应用停留在启动页，目前发现该现象出现在Android OS 4.4.0，Android 6.0未发现此现象

**Comment by lemon-go** [comment]
更正： 在所有Android手机上点击消息都会出现重启现象，但Android 4.4.0上重启后会停留在启动页不动，Android 6.0 可以正常进入！

**Comment by lhw5123** [comment]
是使用 demo 测试的吗？我这里在 Android 4.4.0 的模拟器中运行 demo，并没有出现这个现象。

**Comment by lemon-go** [comment]
我运行DEMO也不存在这个现象，我是使用eclipse ADT 集成，我担心是不是我集成的问题，我的集成步骤如下：

- 拷贝demo中 `io.dcloud.feature.jpush` 文件夹至 `src` 下

- 按照 [极光推送官网](https://docs.jiguang.cn/jpush/client/Android/android_guide/#_5) 集成了 `jar包`、`so`文件、资源文件和配置文件

- 项目页面（html）中引入从DEMO中拷贝的 `jpush.js`

按照如上所说的步骤集成成功后能初始化、设置别名标签、接收通知消息；但是当用户点击同通知消息就会使得应用重新启动，这是什么问题呢？谢谢~

**Comment by lemon-go** [comment]
DEMO中的效果正常，即：**应用正在运行时，点击通知消息只会将应用拉到前台，不会重启应用；但我集成后所有Android机在点击消息后都会重启。**
望知悉，多谢！

**Comment by lhw5123** [comment]
可以试下用 Android Studio 集成，Eclipse ADT 有些老了，Google 也放弃维护了，我个人强烈推荐尝试一下 Android Studio。Demo 就是用 Android Studio 集成的。你的步骤也没什么问题，目前能看出的差异可能就在这里。

**Comment by lemon-go** [comment]
好的，谢谢
